<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 14 Nov 2012 02:15:16 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'accounting_quickbooks' => 
  array (
    'setup_password' => '47ddb5e4a420',
    'setup_username' => 'sean@modifywatches.com',
    'setup_fileid' => 'bb536a24',
  ),
);
