<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Mon, 13 Feb 2012 20:23:51 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'addon_permissioncheck' => 
  array (
    'is_setup' => '1',
  ),
  'addon_photowall' => 
  array (
    'is_setup' => '1',
  ),
  'addon_verifyfiles' => 
  array (
    'is_setup' => '1',
  ),
);
