<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 31 Jan 2013 19:06:45 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'analytics_googleanalytics' => 
  array (
    'is_setup' => '1',
    'trackingcode' => '<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push([\'_setAccount\', \'UA-17528749-1\']);
  _gaq.push([\'_trackPageview\']);

  (function() {
    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;
    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';
    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>',
  ),
  'analytics_shareasale' => 
  array (
    'is_setup' => '1',
    'merchantid' => '45751',
  ),
);
