<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 11 Apr 2013 12:52:29 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_braintree' => 
  array (
    'is_setup' => '1',
    'displayname' => 'Credit Card',
    'merchantid' => '4xz7szfhdwq9jxnq',
    'publickey' => 'jb2xwjw3kc522hzv',
    'privatekey' => '5xg5j9yycwspzhhj',
    'environment' => 'production',
  ),
  'checkout_googlecheckout' => 
  array (
    'is_setup' => '1',
    'merchantid' => '126816192993373',
    'merchanttoken' => '09QB4jLM4kjd9eK69Mxsnw',
    'testmode' => 'NO',
    'fallbackshippingcost' => '6',
    'disablerealtimeshipping' => '1',
    'autoapproveprotected' => 'NO',
    'orderchargestatus' => '11',
  ),
  'checkout_paypalexpress' => 
  array (
    'is_setup' => '1',
    'displayname' => 'PayPal',
    'username' => 'paypal_api1.modifywatches.com',
    'password' => '9VEL8LURWAM65SJJ',
    'signature' => 'AFcWxV21C7fd0v3bYYYRCpSSRl31AOs4tobYnZ75KpE3RRPjxczdW5WP',
    'transactiontype' => 'Sale',
    'testmode' => 'NO',
  ),
);
