<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 08 May 2013 12:54:31 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'customergroupid' => '1',
    'groupname' => 'Free Product (samples, friends, PR)',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  2 => 
  array (
    'customergroupid' => '2',
    'groupname' => 'Non-profit donations',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  3 => 
  array (
    'customergroupid' => '3',
    'groupname' => 'Watch of the Month Club',
    'discount' => '20.0000',
    'discountmethod' => 'percent',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  4 => 
  array (
    'customergroupid' => '4',
    'groupname' => 'B2B Distributors',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  5 => 
  array (
    'customergroupid' => '5',
    'groupname' => 'Retailers',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  6 => 
  array (
    'customergroupid' => '6',
    'groupname' => 'Checkout Testing',
    'discount' => '99.0000',
    'discountmethod' => 'percent',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  7 => 
  array (
    'customergroupid' => '7',
    'groupname' => 'MOTMC Alumni',
    'discount' => '20.0000',
    'discountmethod' => 'percent',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
);
