<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 14 Nov 2012 02:14:01 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => '2',
  1 => '2',
  2 => '2',
  3 => '2',
);
