<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 26 Jun 2013 17:36:51 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'emailintegration_mailchimp' => 
  array (
    'apikey' => 'cc74663a1813641807de09de5965d9c2-us2',
    'isconfigured' => '1',
    'last_list_update' => '1372274162',
  ),
);
