<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Tue, 25 Jun 2013 15:01:42 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'latest' => 'Unknown',
  'lastCheck' => 1372197702,
);
