<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 05 Jun 2013 11:19:13 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'notification_email' => 
  array (
    'is_setup' => '1',
    'emailaddress' => ' aaron@modifywatches.com, ayo@modifywatches.com, michellemodify@gmail.com',
  ),
);
