<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 01 Aug 2012 15:46:42 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    2 => 
    array (
      'pagetitle' => 'Shipping & Returns',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '2',
      'pagecustomersonly' => '0',
    ),
    3 => 
    array (
      'pagetitle' => 'Contact Us',
      'pagetype' => '3',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '3',
      'pagecustomersonly' => '0',
    ),
    1 => 
    array (
      'pagetitle' => 'RSS Syndication',
      'pagetype' => '0',
      'pagelink' => '',
      'pageparentid' => '0',
      'pageid' => '1',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);
