<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Tue, 13 Nov 2012 20:04:41 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    61 => 
    array (
      'categoryid' => '61',
      'catparentid' => '0',
      'catname' => 'Artist Collaborations',
      'catdepth' => '0',
    ),
    94 => 
    array (
      'categoryid' => '94',
      'catparentid' => '0',
      'catname' => 'Best Sellers',
      'catdepth' => '0',
    ),
    60 => 
    array (
      'categoryid' => '60',
      'catparentid' => '0',
      'catname' => 'Brands You Love',
      'catdepth' => '0',
    ),
    63 => 
    array (
      'categoryid' => '63',
      'catparentid' => '0',
      'catname' => 'Community Voted',
      'catdepth' => '0',
    ),
    58 => 
    array (
      'categoryid' => '58',
      'catparentid' => '0',
      'catname' => 'Core Colors',
      'catdepth' => '0',
    ),
    93 => 
    array (
      'categoryid' => '93',
      'catparentid' => '0',
      'catname' => 'New Products',
      'catdepth' => '0',
    ),
    62 => 
    array (
      'categoryid' => '62',
      'catparentid' => '0',
      'catname' => 'Non-Profit',
      'catdepth' => '0',
    ),
    59 => 
    array (
      'categoryid' => '59',
      'catparentid' => '0',
      'catname' => 'Patterns',
      'catdepth' => '0',
    ),
    92 => 
    array (
      'categoryid' => '92',
      'catparentid' => '0',
      'catname' => 'Sale Items',
      'catdepth' => '0',
    ),
  ),
  61 => 
  array (
    85 => 
    array (
      'categoryid' => '85',
      'catparentid' => '61',
      'catname' => 'Martin Hsu',
      'catdepth' => '1',
    ),
  ),
  60 => 
  array (
    81 => 
    array (
      'categoryid' => '81',
      'catparentid' => '60',
      'catname' => 'Cal',
      'catdepth' => '1',
    ),
    77 => 
    array (
      'categoryid' => '77',
      'catparentid' => '60',
      'catname' => 'Deadmau5',
      'catdepth' => '1',
    ),
    79 => 
    array (
      'categoryid' => '79',
      'catparentid' => '60',
      'catname' => 'Domo',
      'catdepth' => '1',
    ),
    84 => 
    array (
      'categoryid' => '84',
      'catparentid' => '60',
      'catname' => 'Louisville 2013',
      'catdepth' => '1',
    ),
    80 => 
    array (
      'categoryid' => '80',
      'catparentid' => '60',
      'catname' => 'MLB',
      'catdepth' => '1',
    ),
    82 => 
    array (
      'categoryid' => '82',
      'catparentid' => '60',
      'catname' => 'Pac-12',
      'catdepth' => '1',
    ),
    83 => 
    array (
      'categoryid' => '83',
      'catparentid' => '60',
      'catname' => 'Rock the Vote',
      'catdepth' => '1',
    ),
    78 => 
    array (
      'categoryid' => '78',
      'catparentid' => '60',
      'catname' => 'Tetris',
      'catdepth' => '1',
    ),
  ),
  63 => 
  array (
    89 => 
    array (
      'categoryid' => '89',
      'catparentid' => '63',
      'catname' => 'Blue Birds',
      'catdepth' => '1',
    ),
    91 => 
    array (
      'categoryid' => '91',
      'catparentid' => '63',
      'catname' => 'QR',
      'catdepth' => '1',
    ),
    90 => 
    array (
      'categoryid' => '90',
      'catparentid' => '63',
      'catname' => 'Red Birds',
      'catdepth' => '1',
    ),
    88 => 
    array (
      'categoryid' => '88',
      'catparentid' => '63',
      'catname' => 'USA',
      'catdepth' => '1',
    ),
  ),
  58 => 
  array (
    64 => 
    array (
      'categoryid' => '64',
      'catparentid' => '58',
      'catname' => 'Black',
      'catdepth' => '1',
    ),
    69 => 
    array (
      'categoryid' => '69',
      'catparentid' => '58',
      'catname' => 'Blue',
      'catdepth' => '1',
    ),
    67 => 
    array (
      'categoryid' => '67',
      'catparentid' => '58',
      'catname' => 'Gold',
      'catdepth' => '1',
    ),
    68 => 
    array (
      'categoryid' => '68',
      'catparentid' => '58',
      'catname' => 'Green',
      'catdepth' => '1',
    ),
    72 => 
    array (
      'categoryid' => '72',
      'catparentid' => '58',
      'catname' => 'Orange',
      'catdepth' => '1',
    ),
    70 => 
    array (
      'categoryid' => '70',
      'catparentid' => '58',
      'catname' => 'Pink',
      'catdepth' => '1',
    ),
    71 => 
    array (
      'categoryid' => '71',
      'catparentid' => '58',
      'catname' => 'Purple',
      'catdepth' => '1',
    ),
    66 => 
    array (
      'categoryid' => '66',
      'catparentid' => '58',
      'catname' => 'Silver',
      'catdepth' => '1',
    ),
    65 => 
    array (
      'categoryid' => '65',
      'catparentid' => '58',
      'catname' => 'White',
      'catdepth' => '1',
    ),
  ),
  62 => 
  array (
    87 => 
    array (
      'categoryid' => '87',
      'catparentid' => '62',
      'catname' => 'Street Soccer USA',
      'catdepth' => '1',
    ),
    86 => 
    array (
      'categoryid' => '86',
      'catparentid' => '62',
      'catname' => 'Together',
      'catdepth' => '1',
    ),
  ),
  59 => 
  array (
    76 => 
    array (
      'categoryid' => '76',
      'catparentid' => '59',
      'catname' => 'Argyle',
      'catdepth' => '1',
    ),
    73 => 
    array (
      'categoryid' => '73',
      'catparentid' => '59',
      'catname' => 'Polka',
      'catdepth' => '1',
    ),
    74 => 
    array (
      'categoryid' => '74',
      'catparentid' => '59',
      'catname' => 'Stripes',
      'catdepth' => '1',
    ),
    75 => 
    array (
      'categoryid' => '75',
      'catparentid' => '59',
      'catname' => 'Zebra',
      'catdepth' => '1',
    ),
  ),
);
