<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 11 Jan 2012 12:39:38 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  '' => 
  array (
  ),
);
